apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-db-instance.ct06e24242ry.eu-west-2.rds.amazonaws.com:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mysql-db-instance.ct06e24242ry.eu-west-2.rds.amazonaws.com:3306/foodcataloguedb
  userdb_url: jdbc:mysql://mysql-db-instance.ct06e24242ry.eu-west-2.rds.amazonaws.com:3306/userdb
  orderdb_url: mongodb+srv://admin:czZPM8Z1w0n7LrTP@atlas-cluster.fkstyot.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka

